### ISSUE TITLE
Is the project ready?

### ISSUE THREAD

**Issue by dbf256** [KevinBusse/cg-referee-code4life#1]
Hi, I've tried your pre-build jar and latest version of cg-brutaltaster (https://github.com/dreignier/cg-brutaltester/tree/master/src/main/java/com/magusgeek/brutaltester) using such files:

`java -jar C:\Projects\cg-brutaltester\target\cg-brutaltester-0.0.1-SNAPSHOT.jar -r ref.bat -p1 first.bat -p2 second.bat -t 2 -n 2 -l "logs"`

ref.bat
`java -jar cg-c4l.jar `

first.bat
```
cd C:\Projects\codeforlife\out\production\codeforlife\
java Player
```

second.bat
```
cd C:\Projects\codeforlife\out\production\codeforlife\
java Player
```

Two files are created (game1.log, game2.log), but they contains only 11 bytes:

`Referee: 

`

So am I wrong with setup or project is not completed yet?
Thanks.

**Comment by kevinsandow** [comment]
I'm really sorry for the confusion (and for the mess I left online), but I had barely the time to get to bronze.

I then converted my solution from JavaScript to Go... and I'm using cg-brutaltester with the following command:

```java -jar cg-brutaltester.jar -r "java -jar cg-c4l.jar" -p1 cg-code4life.exe -p2 c4l-wait.exe```

But in theory the `.bat` solution should just work as well.

**Comment by dbf256** [comment]
Thanks, Kevin. 
It was a problem because I've made a "cd" command inside my bat files.
For those who will get here and using java - this is a working line:


`java -jar C:\Projects\cg-brutaltester\target\cg-brutaltester-0.0.1-SNAPSHOT.jar -r "java -cp C:\Projects\codeforlife\out\production\codeforlife\ Referee" -p1 "java -cp C:\Projects\codeforlife\out\production\codeforlife\ Player" -p2 "java -cp C:\Projects\codeforlife\out\production\codeforlife\ Player" -t 2 -n 2 -l "logs"`

Thanks again for your tool!
